# Generated by Django 3.1.6 on 2021-02-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210216_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='followers',
            name='created',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='upvotes',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
