# Generated by Django 3.1.6 on 2021-02-16 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210216_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='followee',
        ),
        migrations.AddField(
            model_name='followers',
            name='followee',
            field=models.ManyToManyField(related_name='followee', to=settings.AUTH_USER_MODEL),
        ),
    ]
