# Generated by Django 3.1.6 on 2021-02-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210216_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='follower',
            new_name='followers',
        ),
    ]
