# Generated by Django 3.1.3 on 2021-02-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20210216_1418'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
