# Generated by Django 3.1.6 on 2021-08-02 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20210216_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='owner',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
