# Generated by Django 3.1.6 on 2021-08-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_auto_20210802_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='hello', verbose_name='user-profile'),
            preserve_default=False,
        ),
    ]
