# Generated by Django 3.1.6 on 2021-08-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20210810_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(verbose_name='profile url'),
        ),
    ]
