# Generated by Django 3.1.6 on 2021-08-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_auto_20210810_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_slug',
            field=models.SlugField(blank=True, null=True, verbose_name='profile img url'),
        ),
    ]
