# Generated by Django 3.1.3 on 2021-08-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_auto_20210810_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='edited',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='date edited'),
        ),
    ]
