# Generated by Django 3.1.3 on 2021-08-12 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_posts_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvotes',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='network.posts'),
        ),
    ]
