# Generated by Django 3.1.3 on 2021-08-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_auto_20210812_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_slug',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, null=True, verbose_name='profile img url'),
        ),
    ]
